### ISSUE TITLE
Problems with received messages (code status 204)

### ISSUE THREAD

**Issue by EliottPaillard** [ISAITB/gitb#48] opened 2024-04-11 14:02 UTC
Hello,
I'm using the 1.21.1 version and I spotted something unpleasant with the ITB.
I use a <send> with the httpmessaging handler sending a POST request from my simulated actor to my SUT and expecting a 204 No Content in response from it.
After this I use a <receive> in which there is a <config name="code.status"> expecting this 204 code.
Then this step just never ends.
I tried to add a timeout, but this often fails the step.

There is no doubt that the SUT actually respond to the request with a 204.
Besides, I didn't have any problems with 201 and 200 codes when I have to waiting for them.

Any thoughts about this?
Thank you!

**Comment by costas80** [comment] 2024-04-11 14:26
Hi @EliottPaillard. Its difficult to understand what you're going for. You mention:

> I use a with the httpmessaging handler ...

and

> After this I use a in which ...

What is the "a" you are mentioning? If I understood your SUT sends a 204 but this is not picked up from the messaging handler right?

Is it possible to share here a simple test case that replicates the issue? I could then try to replicate it.

By the way the HttpMessaging handler - all embedded messaging handlers actually - are components we started advising to not use directly. They necessitate (in their current state) direct exposure of the internal test engine to SUTs which is not ideal. The approach we advise is to use a [custom messaging service](https://www.itb.ec.europa.eu/docs/services/latest/messaging/index.html) alongside the Test Bed (a good starting point currently is to use our [template services](https://www.itb.ec.europa.eu/docs/services/latest/templates/index.html)).

**Comment by EliottPaillard** [comment] 2024-04-11 14:56
Hey,
Thanks for this quick answer!
Indeed, I used xml tags in my message but they are not seeable.
Here is the simple example of what I'm going for.

<img width="598" alt="image" src="https://github.com/ISAITB/gitb/assets/143092948/c25caa76-7d4a-4882-adf7-b42fcf5da128">
 
As said upper, on the ITB the receive step never stops.

I wasn't aware of what you said about the custom messaging service, thank you for that!

**Comment by costas80** [comment] 2024-04-11 15:18
It would be a lot faster to replicate if you could share the test suite archive you are using. Could you add it here as an attachment?

**Comment by EliottPaillard** [comment] 2024-04-11 15:35
Sure, here it is
[test.zip](https://github.com/ISAITB/gitb/files/14948229/test.zip)

**Comment by costas80** [comment] 2024-04-12 10:28
The problem was due to the handling of the 204 code specifically, as the Test Bed would block reading the response body. This was wrong however given that 204 specifically means "no content".

The fix is now available in this repo's **development** branch and also published in our **nightly build** channel (the latter being the most efficient way to get development updates before being published in a release). If you are new to our nightly builds, please check the docs [here](https://www.itb.ec.europa.eu/docs/guides/latest/onboardingDevelopers/index.html#using-nightly-builds).

Now, even though this issue is fixed, I would still strongly advise you avoid using the deprecated `HttpMessaging` handler. We plan to provide soon a new messaging handler for making simple HTTP calls, but if you want to have test cases both send and receive messages to/from the SUT ("receive" here meaning that the SUT initiates the contact with the Test Bed) you will be much better served by a custom messaging handler that implements your API and notifies the Test Bed on received calls. I have posted previously in the thread the documentation links to get started with this.

Regarding this specific issue @EliottPaillard, would you please close this issue once you confirm the problem is resolved?

**Comment by costas80** [comment] 2024-04-12 10:35
By the way I noticed in your sample test case that you asked whether you need the `variables` section. The answer is that you don't considering that variables (assign and send/receive outputs) are created on the fly if not already existing. You only need declare variables in very niche cases if you want to make certain that a given value/content is treated as a specific data type.

**Comment by costas80** [comment] 2024-04-12 10:40
Oh and one final comment based on your sample test suite :)

Most test cases benefit from immediately stopping when an error is encountered (versus continuing to go through subsequent steps). You do this by setting `stopOnError="true"` on the test case `steps` element (see [here](https://www.itb.ec.europa.eu/docs/tdl/latest/testcase/index.html#steps)):
```xml
<steps stopOnError="true">
   ...
</steps>
```

**Closed** 2024-04-15 15:39 UTC
Labels: bug
