### ISSUE TITLE
Bug when using http.uri.extension in a scriplet

### ISSUE THREAD

**Issue by EliottPaillard** [ISAITB/gitb#53] opened 2024-05-23 08:21 UTC
Hey,

trying to add scriptlets lately to make my test cases more readable, I've found a bug with the http.uri.extension.

You'll find an example exposing well what I'm talking about : 
[example.zip](https://github.com/ISAITB/gitb/files/15413854/example.zip)

As you can see, I use the scriptlet three time, I put the variable $entityId as an input for it.

Firstly the scriptlet log the value of the variable, which is indeed updated as it should be.

However the http.uri.extension is getting stuck to the first value of $entityId.

I'm using the nightly build btw

**Comment by costas80** [comment] 2024-05-23 11:31
Hi @EliottPaillard. Unfortunately this is not a bug, its how the `config` elements work. They are meant to be set with fixed values and not expressions that can be evaluated at runtime, in contrast to the `log` step which takes an expression and prints as expected the parameter value (evaluated at runtime).

This is another good example of why you should switch to the new `HttpMessagingV2` handler as discussed in #50. The new handler uses only inputs allowing you to manage at runtime all aspects of the HTTP calls. Using the new handler, your scriptlet would become as follows:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<scriptlet id="deleteEntity" xmlns="http://www.gitb.com/tdl/v1/">
    <params>
        <var name="entityId" type="string"/>
    </params>
    <steps>
        <send desc="Delete entity" from="SimulatedActor" to="ContextBroker" handler="HttpMessagingV2">
	     <input name="method">"DELETE"</config>
             <input name="uri">$SYSTEM{endpointAddress} || "ngsi-ld/v1/temporal/entities/" || $entityId</config>
        </send>
    </steps>
</scriptlet>
```

**Comment by costas80** [comment] 2024-06-07 13:29
Closing this issue as the described behaviour can be achieved through the new `HttpMessagingV2` handler (sample snippet provided in the previous comment).

**Closed by costas80** 2024-06-07 13:29 UTC
Labels: question
