### ISSUE TITLE
API REST error

### ISSUE THREAD

**Issue by Nicolas-Caroff** [ISAITB/gitb#64] opened 2024-07-17 15:31 UTC
Hello, 

I'm trying to use ITB REST API to execute a test suite. But I get a 400 bad request response when I'm doing this request :
curl --location 'https://<SERVER_NAME>/itb-dev/api/rest/tests/start' \
--header 'ITB_API_KEY: E41394CFX73FDX4FD2XA1E8X08CF499967D8' \
--header 'Content-Type: application/json' \
--data '{
  "system": "7FA403A7X4416X4A43X966DXDE166FB26A87",
  "actor": "B50327A6X1791X492EXBC70XAA566FB3AC5E",
  "testSuite": [ "OGC_validation" ]
}'
The response is this : 
<img width="322" alt="image" src="https://github.com/user-attachments/assets/85625144-54dd-4cee-897c-966051b0cfe8">

Do you have an idea about the problem ?

**Comment by costas80** [comment] 2024-07-17 20:39
Your request seems ok so there's no obvious issue from there. What is odd however is that you're getting an HTML error page which means that the REST API is not processing your request (you would get a JSON response if the request was correctly received and resulted in an error).

Are you already using the REST API for other calls or is this the first time you try it? If it's the first time then you should first make sure it's enabled (it's disabled by default). If enabled then you can try [loading the API in Swagger UI](https://www.itb.ec.europa.eu/docs/itb-ta/latest/api/index.html#openapi-documentation) and making the same call from there. If that works then you know there's something wrong in the curl request that we've missed.

Finally, we can check the error's stacktrace from the logs of the `gitb-ui` container (or `itb-ui` depending on the naming). This should pinpoint the cause of the issue (note that you can lookup the error with the reported error code as well). If you check the logs and the error is not obvious then please post here the relevant stacktrace.

**Comment by costas80** [comment] 2024-07-31 14:05
Closing as @Nicolas-Caroff confirmed in #69 this issue no longer comes up.

**Closed by costas80** 2024-07-31 14:05 UTC
