### ISSUE TITLE
Number addition not working

### ISSUE THREAD

**Issue by EliottPaillard** [ISAITB/gitb#65] opened 2024-07-18 07:24 UTC
Hey @costas80,

I used this documentation : https://www.itb.ec.europa.eu/docs/tdl/latest/expressions/index.html
And particularly this lines:
<img width="359" alt="image" src="https://github.com/user-attachments/assets/fcfef49c-ce66-4c52-bbb4-a77059e8b03f">

But ITB doesn't like that syntax.
[example.zip](https://github.com/user-attachments/files/16279287/example.zip)

I didn't find yet how to make a simple addition.

**Comment by costas80** [comment] 2024-07-18 07:56
Hi @EliottPaillard. Indeed that seems like it should be working plus I reproduced locally (thanks for providing an example that reproduces the issue). I'm looking further into this now and will keep you posted.

**Comment by costas80** [comment] 2024-07-18 09:08
The problem was due to the test suite validation incorrectly handling arithmetic operations that contained variable expressions. The fix is published on the [nightly build channel](https://www.itb.ec.europa.eu/docs/guides/latest/onboardingDevelopers/index.html#using-nightly-builds) that you can pull to correct this on your end (the fix will be included in the next stable release). 

@EliottPaillard, could you confirm once you've had the chance to retest on your end?

**Comment by EliottPaillard** [comment] 2024-07-18 09:42
It works now :)
Thank you !

**Closed** 2024-07-18 09:43 UTC
Labels: bug
